environment:
  matrix:
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"

install:
  - "%PYTHON%\\python.exe -m pip install --requirement requirements.txt"

build: off

test_script:
  - "%PYTHON%\\python.exe -m invoke"
