language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

matrix:
  allow_failures:
    - os: osx # Python 3 not supported in Travis OSX environment
    - python: "3.6" # not supported
    - python: "nightly"

os:
  - linux
  - osx

install:
  - "source ~/virtualenv/python2.7/bin/activate"
  - "scons setup"
  - "source ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/activate"

script:
  - "source ~/virtualenv/python2.7/bin/activate"
  - "scons"
  - "source ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/activate"
